image : openjdk:8-alpine

stages:
- build
- test
- package



build-job:
    stage: build
    script: ./gradlew assemble

test-job:
   stage: test
   script: ./gradlew test

package-job:
    stage: package
    script:
    - ./gradlew bootJar
    artifacts:
      paths:
        - /builds/Jerome_CM/tourGuide/build/libs/tourGuide-1.0.0.jar
